-- AlterTable
ALTER TABLE "Company" ADD COLUMN     "address" TEXT,
ADD COLUMN     "bankInfo" TEXT,
ADD COLUMN     "eurToTry" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN     "logoUrl" TEXT,
ADD COLUMN     "phone" TEXT,
ADD COLUMN     "taxId" TEXT,
ADD COLUMN     "usdToTry" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN     "vatRate" DOUBLE PRECISION NOT NULL DEFAULT 20;

-- AlterTable
ALTER TABLE "SoleCalculation" ADD COLUMN     "laborCurrency" TEXT NOT NULL DEFAULT 'USD',
ADD COLUMN     "sellingPriceWithVat" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "vatRate" DOUBLE PRECISION NOT NULL DEFAULT 0;
